// Do not edit this file!
// This file may only be edited by Engima's ASCOM Editor!
//
// <ASCOM version="1">
// <Prefix>pain_</Prefix>
// <Functions>
// <Function Name="playAnimation" Params="player, animation" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// <Function Name="attachToCar" Params="player, car, seat" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// <Function Name="selecHeight" Params="type" Ret="true" A="false" C="false" S="true" O="false" OC="false" P="false" />
// </Functions>
// </ASCOM>

ASCOM_ClientID = 0;
ASCOM_CallID = 0;
ASCOM_LastCallID = 0;
ASCOM_LockCallID = 0;

"pain_playAnimationEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call pain_playAnimation;
        };
    };
};

pain_playAnimationAll = {
    if (isNil "_this") then { _this = []; };
    pain_playAnimationEventArgs = ["A", _this];
    publicVariable "pain_playAnimationEventArgs";
    _this call pain_playAnimation;
    pain_playAnimationEventArgs = [];
};


"pain_attachToCarEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call pain_attachToCar;
        };
    };
};

pain_attachToCarAll = {
    if (isNil "_this") then { _this = []; };
    pain_attachToCarEventArgs = ["A", _this];
    publicVariable "pain_attachToCarEventArgs";
    _this call pain_attachToCar;
    pain_attachToCarEventArgs = [];
};


"pain_selecHeightEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call pain_selecHeight;
        };

        if (_this select 0 == "S" && isServer) then {
            private ["_response"];

            _response = (_this select 3) call pain_selecHeight;

            pain_selecHeightResponse = [_this select 1, _this select 2, _response];
            publicVariable "pain_selecHeightResponse";
        };
    };
};

pain_selecHeightResponse = [0, 0];
pain_selecHeightResponseValue = [0, 0];

"pain_selecHeightResponse" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    if (_array select 0 == ASCOM_ClientID) then {
        _array spawn {
            waitUntil { ASCOM_LockCallID == 0 };
            ASCOM_LockCallID = _this select 1;
            pain_selecHeightResponseValue = _this;
        };
    };
};

pain_selecHeightServer = {
    private ["_response"];
    if (isNil "_this") then { _this = []; };

    if (isServer) then {
        // A 'generic error in expression' here may indicate that you have forgotten to return a value from function pain_selecHeight.
        _response = _this call pain_selecHeight;
    }
    else {
        private ["_callID"];

        ASCOM_CallID = ASCOM_CallID + 1;
        _callID = ASCOM_CallID;
        pain_selecHeightEventArgs = ["S", ASCOM_ClientID, _callID, _this];
        publicVariable "pain_selecHeightEventArgs";

        waitUntil { (pain_selecHeightResponseValue select 1) == _callID };

        _response = pain_selecHeightResponseValue select 2;
        ASCOM_LockCallID = 0;
    };

    _response
};



if (isServer) then {
    "ASCOM_AskForClientID" addPublicVariableEventHandler {
        private ["_unit"];

        _unit = _this select 1;
        ASCOM_AskForClientID = [];
        ASCOM_LastCallID = ASCOM_LastCallID + 1;
        ASCOM_ClientIDResponse = [_unit, ASCOM_LastCallID];
        publicVariable "ASCOM_ClientIDResponse";
    };

    ASCOM_ServerInitialized = true;
    publicVariable "ASCOM_ServerInitialized";
    ASCOM_Initialized = true;
}
else {
    "ASCOM_ClientIDResponse" addPublicVariableEventHandler {
        private ["_array"];

        _array = _this select 1;
        ASCOM_ClientIDResponse = [];

        if (player == (_array select 0)) then {
            ASCOM_ClientID = _array select 1;
            ASCOM_Initialized = true;
        };
    };

    waitUntil {!isNull player};
    ASCOM_AskForClientID = player;
    publicVariable "ASCOM_AskForClientID";
};
